services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hikkoshilens-backend
    working_dir: /app
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - MLIT_API_KEY=${MLIT_API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
        NEXT_PUBLIC_MLIT_API_KEY: ${NEXT_PUBLIC_MLIT_API_KEY}
    container_name: hikkoshilens-frontend
    profiles: ["prod"]
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
      - NEXT_PUBLIC_MLIT_API_KEY=${NEXT_PUBLIC_MLIT_API_KEY}
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend-dev:
    profiles: ["dev"]
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: hikkoshilens-frontend-dev
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
      - NEXT_PUBLIC_MLIT_API_KEY=${NEXT_PUBLIC_MLIT_API_KEY}
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
